config/routes.rb
Rails.application.routes.draw do
  resources :listings
  # devise_for :users
  root to: "pages#index"
	
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'registrations' }

	resources :users, only: [:show]
  
  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  # No route matches [GET] "/users/sign_out"に対する対処
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # get 'pages/index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos
  #必須項目
  validates :home_type, presence: true
  validates :pet_type, presence: true
  validates :pet_size, presence: true
  validates :breeding_years, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :listing
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
    
    has_many :listings
    # @user.listings

	  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	    # If you are using confirmable and the provider(s) you use validate emails, 
	    # uncomment the line below to skip the confirmation emails.
	    # user.skip_confirmation!
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:phone_number,:description])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:update, :basics, :description, :address, :price, :photos, :calendar, :bankaccount, :publish]
  def index
  end

  def show
  end

  def new
    #現在のユーザーのリスティング作成
    @listing = current_user.listings.build
  end

  def create
    #パラメーターとともに現在のユーザーのリイスティングを作成
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      redirect_to manage_listing_basics_path(@listing), notice:"リスティングを作成保存しました"
    else
      redirect_to new_listing_path, notice:"リスティングを作成保存できませんでした"
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to manage_listing_basics_path(@listing), notice: "更新できました"
    end
  end

  def basics
  end

  def description
  end

  def address
  end

  def price
  end

  def photos
    @photo = Photo.new
  end

  def calendar
  end

  def bankaccount
  end

  def publish
  end
  
  private
  def listing_params
    params.require(:listing).permit(:home_type, :pet_type, :breeding_years, :address, :publish, :pet_size, :price_pernight)   
  end

  def set_listing
    @listing = Listing.find(params[:id]) 
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    def create
        @photo = Photo.new(photo_params)
        if @photo.save
            render json: { message: "success", photoId: @photo.id }, status: 200
        else
            render json: { error: @photo.errors.full_messages.join(", ") }, status: 400
        end
    end

    def destroy
        @photo = Photo.find(params[:id])
        if @photo.destroy
            render json: { message: "file deleted from server" }
        else
            render json: { message: @photo.errors.full_messages.join(", ") }
        end
    end

    def list
        listing = Listing.find(params[:listing_id])

        photos = []
        Photo.where(listing_id: listing.id).each do |photo|
            new_photo = {
                id: photo.id,
                name: photo.image_file_name,
                size: photo.image_file_size,
                src: photo.image(:thumb)
            }
            photos.push(new_photo)
        end
        render json: { images: photos }
    end

    private
    def photo_params
        params.require(:photo).permit(:image,:listing_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	  def facebook
	    # You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.from_omniauth(request.env["omniauth.auth"])

	    if @user.persisted?
	      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
	      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
	    else
	      session["devise.facebook_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	  end

	  def failure
	    redirect_to root_path
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@moji = "ようこそ、いらっしゃいませ"
  	#Userモデルから、userを探してきた。
  	#facebook使用時のみ使える↑
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def controller?(controller)
		# 引数が現在のコントローラーに含まれていたらtrueを返す
		controller.include?(params[:controller])		
	end

	def action?(action)
		action.include?(params[:action])		
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
<!--       <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
<!-- flashにメッセージがあある時 -->
  <% unless flash.empty? %>
        <script type="text/javascript">
            <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
              toastr['<%= type %>']('<%= f[1] %>');
            <% end %>
        </script>
  <% end %>
  </body>
</html>

app/views/listings/address.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">住所の編集</span>
                </div>
            </div>

            <div class="panel-body">          

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>住所</label>
                                <%= f.text_field :address, placeholder: "例: 東京都港区六本木６丁目１１−１", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/bankaccount.html.erb
bankaccount.html.erb

app/views/listings/basics.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              <div class="text-center">
                  <span style="font-size:24px;">基本データの編集</span>
              </div>
          </div>

          <div class="panel-body">           
              <%= form_for @listing do |f| %>
                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>お家の種類</label>
                              <%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの種類</label>
                              <%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの飼育歴</label>
                              <%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットのサイズ</label>
                              <%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="actions">
                      <%= f.submit "更新", class: "btn btn-danger" %>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/listings/calendar.html.erb
bankaccount.html.erb

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/description.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング内容の編集</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>タイトル</label>
                                <%= f.text_field :listing_title, placeholder: "リスティングタイトルを記載しましょう", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>内容</label>
                                <%= f.text_area :listing_content, rows: 8, placeholder: "リスティングの内容について記述してください", class: "form-control" %>
                            </div>                            
                        </div>
                    </div>
            

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

app/views/listings/new.html.erb
<%= render 'partial/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="text-center">
						<span style="font-size:24px;">ペットリスティングを掲載する</span>
					</div>
				</div>
			
				<div class="panel-body">			
					<!-- ここからフォーム -->
					<%= form_for @listing do |f| %>
						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>お家の種類</label>
									<%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットの種類</label>
									<%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットの飼育歴</label>
									<%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットのサイズ</label>
									<%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="actions">
							<%= f.submit "Save", class: "btn btn-danger" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/listings/photos.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング写真の編集</span>
                </div>
            </div>

            <div class="panel-body">          
                <%= form_for @photo, html:{multipart: true,class:"dropzone", id:"my-dropzone" } do |f| %> 
                    
                    <%= f.hidden_field :listing_id, value: @listing.id %>
                    <div class="dz-message needsclick">
                        <h3>ファイルをここにドロップしてください。</h3>
                        <strong>アップロードするにはここをクリックしてください</strong>
                    </div>
                    
                    <div class="fallback">
                        <%= f.file_field :image %>
                        <%= f.submit "Upload image" %>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>
<!-- dropzone.js -->
<script type="text/javascript">
  $(function () {
  Dropzone.autoDiscover = false;
  //photos_controller.rbのcreateアクションが呼ばれる
  $("#my-dropzone").dropzone({
    maxFilesize: 200,// MB
    addRemoveLinks: true,//削除リンク,Cancelリンクを全てのpreviewファイルに付ける。 
    paramName: 'photo[image]',// パラメータの名前
    success: function(file, response) {
      // file.previewElementでpreview要素のhtmlにアクセスできる
      //add .dz-success class to file.previewElement 
      $(file.previewElement).addClass('dz-success');
      //add response.uploadId to .dz-remove class
      $(file.previewElement).find('.dz-remove').attr('id', response.photoId);
    },
    removedfile: function(file) {
      // 削除選択されたfileのidを取得
      var id = $(file.previewTemplate).find('.dz-remove').attr('id');
      //call photos_controler.rb destroy action
      $.ajax({
        type: 'DELETE',
        url: "/photos/" + id,
        success: function(data) {
          console.log(data.message);
        }
      });

      var previewElement;
      // 条件式 ? 式1 : 式2　条件式の値がtrue=>式1、false=>式2返します。
      //parentNode => 親ノード（一つ上のhtml要素)を取得.
      //(void 0) => 何も処理しない
      // リスト（親ノード）から、プレビュー要素を消すという記述
      return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
    },
    // init executed at first when Page loaded
    init: function() {
      //this equal dropzone
      var me = this;

      //meに"complete"イベントを定義
      me.on("complete", function(file) {
       $(file.previewTemplate).find('.dz-remove').text("削除する");
      }); 
      //call list function in photos_controller.rb with get method
      $.ajax({
       type: "GET",
       url: "/photos/list",
       data: {'listing_id': <%= @listing.id %>},
           dataType: 'json',
       success: function(data){
           $.each(data.images, function(key, value) {
             if (data.images != undefined && data.images.length > 0) {
               me.emit("addedfile", value); //addedfileイベントをvalueのデータで実行する
               me.emit("thumbnail", value, value.src);//thumbnailイベントをvalueのデータで実行する
               me.emit("complete", value);  //completeイベントをvalueのデータで実行する
               $(value._removeLink).attr("id", value.id); //valueの_removeLinkのidにvalue.idを追加
             }
           });
       }
      });
    }
  });
});
</script>

app/views/listings/price.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">料金の設定</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label>一泊あたりの料金</label>
                          <div class="input-group">
                            <div class="input-group-addon">円</div>
                            <%= f.text_field :price_pernight, placeholder: "例: 100", class: "form-control" %>
                          </div>  
                        </div>
                      </div>
                    </div>    

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/publish.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">公開する</span>
                </div>
            </div>

            <div class="panel-body">            

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                            <%= f.select :active, [["公開する","true"], ["非公開にする","false"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                        </div>
                      </div>
                    </div>
        
                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/show.html.erb
<h1>Listings#show</h1>
<p>Find me in app/views/listings/show.html.erb</p>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/pages/index.html.erb
<script type="text/javascript">
  $(function(){
      $(".navbar").removeClass("navbar-devise");
      $(".navbar").addClass("navbar-default");
  });
</script>

<div class="jumbotron">
  <%= render 'partial/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <h1 class="display-4">Hello, world!</h1>
        </div>
      </div>
    </div>
</div>


<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/partial/_deviseErrorMsg.html.erb
<!-- deviseにエラーがある場合 -->
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	  <% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

<nav class="navbar navbar-devise">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Brand</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !(user_signed_in?) %>
                <!-- ログインしていない時 -->
                <li><%= link_to "シッターになる", new_listing_path %></li>
                <li><a href="#">利用の流れ</a></li>
                <li><%= link_to "アカウント作成", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
              <% else %>
              <!-- ログインしている時 -->
              <li><%= link_to "シッターになる", new_listing_path %></li>
              <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <% if current_user.provider %>
                          <!-- 認証ログインしている時 -->
                          <%= image_tag current_user.image, class:"img-circle profile-0" %>
                          <% else %>
                            <%= current_user.email %>
                        <% end %>
                      <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "プロフィール", user_path(current_user) %></li>
                        <li><%= link_to "プロフィール編集", edit_user_registration_path %></li>
                        <li><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></li>
                      </ul>
                    </li>
              <% end %>
            </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/partial/_verticalnavbar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?("listings") && action?("basics") %>"><%= link_to "基本事項", manage_listing_basics_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("description") %>"><%= link_to "リスティングの内容", manage_listing_description_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("address") %>"><%= link_to "住所情報", manage_listing_address_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("price") %>"><%= link_to "料金", manage_listing_price_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("photos") %>"><%= link_to "写真", manage_listing_photos_path(@listing),data:{"turbolinks" => false} %></li>
        <li class="<%= 'active' if controller?("listings") && action?("calendar") %>"><%= link_to "カレンダー", manage_listing_calendar_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("bankaccount") %>"><%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %></li>
        <li class="<%= 'active' if controller?("listings") && action?("publish") %>"><%= link_to "公開する", manage_listing_publish_path(@listing) %></li>
        <!-- <li class="active"><a href="#">リスティングの内容</a></li> -->
        <!-- <li><a href="#">住所情報</a></li>
        <li><a href="#">料金</a></li>
        <li><a href="#">写真</a></li>
        <li><a href="#">カレンダー</a></li>
        <li><a href="#">受取口座情報</a></li> -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/users/show.html.erb
<%= render 'partial/navbar' %>

<!-- 認証チェックマーク -->
<script type="text/javascript">
	$(function(){
		<% if !@user.email.blank? %>
			$("#ver-email").attr('class','vertification-checked');
		<% end %>

		<% if !@user.phone_number.blank? %>
			$("#ver-tel").attr('class','vertification-checked');
		<% end %>

		<% if @user.provider == "facebook" %>
			$("#ver-facebook").attr('class','vertification-checked');
		<% end %>
	});
</script>

<div class="container">
	<div class="row">
		<div class="col-lg-3 col-md-4">
			<div class="user-profile row-space-4 text-center">
				<!-- 画像の代わりにメールを表示する FBが使えないため-->
				<%= @user.email %>
				<br>
				<%= @moji %>
			</div>

			<div class="panel panel-default verifications hidden-xs hidden-sm">
				<div class="panel-heading">
					認証済みID
				</div>
				<div class="panel-body">
					<div id="ver-email">
						メールアドレス
					</div>
					<br>
					<div id="ver-tel">
						電話番号
					</div>
					<br>
					<div id="ver-facebook">
						Facebook
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-9 col-md-8 col-sm-12">
			<h1>こんにちわ<%= @user.name %>です!</h1>
			<p>自己紹介</p>
			<%= @user.description %>
		</div>
	</div>  	
</div>